title: Luke Waldron

tagline: Insight Manager and Data Science Student

description: >
  Portfolio of analytical and data science work to support Degree Programme;

author:
  name: Luke Waldron
  location: United Kingdom

theme: jekyll-theme-hyde

markdown: kramdown
highlighter: rouge

# Header image
logo: /images/profile.jpg

# Portfolio intent
show_downloads: false

# GitHub Pages metadata
github:
  is_project_page: false

# Optional but useful
social:
  github: yourusername
  linkedin: yourprofile

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
