title: "Luke Waldron"
description: "Insight Manager | Data Science | FOS Complaints (UK Banking)"
#commentd out old theme 

theme: jekyll-theme-hyde

markdown: kramdown
highlighter: rouge

# Use the Dopetrope theme from the repo you shared
#remote_theme: jeromelachaud/freelancer-theme@master
#plugins:
  #- jekyll-remote-theme


#header image
logo: /Images/9F2B252D-4D27-469D-A35A-E5D706C4B82B.jpeg

# Show download button automatically
show_downloads: false

# GitHub Pages metadata
github:
  is_project_page: false
